#!/usr/bin/env ruby
# frozen_string_literal: true

require "swift_gem/generator"

USAGE = <<~USAGE
  Usage: swift_gem <command> [args]

  Commands:
    new <gem_name> [--dest DIR]   Generate a new swift-gem skeleton
                                  (default DIR is ./<gem_name>/)
    help                          Show this message
USAGE

command = ARGV.shift

case command
when "new"
  gem_name = ARGV.shift
  unless gem_name
    warn USAGE
    exit 1
  end

  dest_dir = nil
  while (arg = ARGV.shift)
    case arg
    when "--dest"
      dest_dir = ARGV.shift
    else
      warn "unknown argument: #{arg}"
      warn USAGE
      exit 1
    end
  end

  dest_dir ||= File.join(Dir.pwd, gem_name)

  if File.exist?(dest_dir) && !Dir.empty?(dest_dir)
    warn "destination already exists and is not empty: #{dest_dir}"
    exit 2
  end

  SwiftGem::Generator.new(gem_name).call(dest_dir: dest_dir)
  puts "Created swift-gem skeleton at #{dest_dir}"
when "help", "--help", "-h", nil
  puts USAGE
  exit 0
else
  warn "unknown command: #{command.inspect}"
  warn USAGE
  exit 1
end
